name: AIPlugin
main: com.example.aiplugin.AIPlugin
version: 1.1.0
api-version: 1.21
author: YourName
commands:
  ai:
    description: Ask the AI anything
permissions:
  aiplugin.admin:
    description: Allow player to use AI admin functions
    default: op
  aiplugin.npc.interact:
    description: Allow player to interact with AI NPCs
    default: true
